name: Auto Pull Request Merge
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: auto-dependabot-pull-request-merge
        uses: KeisukeYamashita/auto-dependabot-pull-request-merge@v1
        with:
          labels: 'dependencies'
          pullRequestNumber: ${{ github.event.pull_request.number }}
